title: "Secondary Nav"
description: |
  Secondary navigation is used to remind the user where they are within the website and to direct the user to the next or previous page from their current site location.

patterns:
  breadcrumb-about-us:
    title: "breadcrumb about us"
    description: |
      This breadcrumb is used to indicate that the user is on the "about us" page
  breadcrumb-cart:
    title: "breadcrumb cart"
    description: |
      This breadcrumb is used to indicate that the user is on the "cart" page
  breadcrumb-checkout:
    title: "breadcrumb checkout"
    description: |
      This breadcrumb is used to indicate that the user is on the "checkout" page
  breadcrumb-prod-page:
    title: "breadcrumb prod page"
    description: |
      This breadcrumb is used to indicate that the user is on the "products" page
  breadcrumb-prod-page-kits:
    title: "breadcrumb prod page kit"
    description: |
      This breadcrumb is used to indicate that the user is on the "product kit" page
  next-prev:
    title: "next prev"
    description: |
      This secondary navigation is used to guide the user to the next or previous page
