title: "Banners"
  description: |
    Banners are used to display information that is consistent across pages. they can be used to unify or differenciate between different types of pages on a website.

patterns:
  homepage-banner:
    title: "Homepage Banner"
      description: |
        This banner is used specifically for the homepage. This banner contains nearly all the information found on the homepage.
  top-of-page-banner:
    title: "Top of Page Banner"
      description: |
        This banner is designed for the top of every page on the website, it contains all of the navigation for the website.
